logging:
    level:
        org:
            springframework: WARN
spring:
    datasource:
        url: jdbc:h2:mem:myspringbootjpa
    h2:
        console:
            enabled: true
            path: /h2
